### ISSUE TITLE
[BUG] No files or folders "utils" and "colors"

### ISSUE THREAD

**Issue by daodreamer** [Envq/panda_gym_integration#1]
Hi there,

This repo is very helpful, but when I opened the scripts like `ai_controller.py`, there was a line `from utils import quaternion_multiply, transform`, and in this repo there is no such files or folders "utils". Could you check it?

Thanks!
 
Best regards

**Comment by Envq** [comment]
Hi thank you.

It's been quite a while since I've worked on this project... but I think the problem is that you don't have panda_controller installed (https://github.com/Envq/panda_controller). Anyway in that repo you will find the files you are talking about.

**Comment by daodreamer** [comment]
> Hi thank you.
> 
> It's been quite a while since I've worked on this project... but I think the problem is that you don't have panda_controller installed (https://github.com/Envq/panda_controller). Anyway in that repo you will find the files you are talking about.

Hi,

thank you for your help! I've installed panda_controller. I thought the utils and colors were located in the folder panda_integration, but they're in panda_controller. Now there is no problem.
